# Generated by Django 5.2.17 on 2026-08-10 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('sur_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sur Name')),
                ('district', models.CharField(max_length=30, verbose_name='District')),
                ('village', models.CharField(max_length=30, verbose_name='Village')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Employies Information',
                'verbose_name_plural': 'Employies Informations',
            },
        ),
    ]
