# Generated by Django 5.2.17 on 2026-08-07 09:24

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('employies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employiesmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='employiesmodel',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.districtmodel', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='employiesmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='employiesmodel',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.provincemodel', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='employiesmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Personal_info', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
