# Generated by Django 5.2.17 on 2026-08-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_districtmodel_province'),
        ('employies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employiesmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.districtmodel', verbose_name='District'),
        ),
    ]
