# Generated by Django 5.2.17 on 2026-08-10 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicerecordingmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voicerecordingmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='voicerecordingmodel',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='voicerecordingmodel',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='voicerecordingmodel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Note / Comments'),
        ),
        migrations.AddField(
            model_name='voicerecordingmodel',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='voicerecordingmodel',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='voicerecordingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
