# Generated by Django 5.2.17 on 2026-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecategorymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
    ]
