# Generated by Django 5.2.17 on 2026-08-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_alter_voicecategorymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecordingmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='recorder.voicecategorymodel', verbose_name='Category'),
        ),
    ]
