# Generated by Django 5.2.17 on 2026-08-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_alter_voicerecordingmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecordingmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='recorder.voicecategorymodel', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
