# Generated by Django 5.2.17 on 2026-08-13 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_alter_voicerecordingmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecordingmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='recorder.voicecategorymodel', verbose_name='Category'),
        ),
    ]
