# Generated by Django 5.2.17 on 2026-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0007_alter_voicerecordingmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecordingmodel',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='Script'),
        ),
    ]
