# Generated by Django 5.2.17 on 2026-08-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ຜົ້ງສາລີ - Phongsaly', 'ຜົ້ງສາລີ - Phongsaly'), ('ຫລວງນ້ຳທາ - Luangnamtha', 'ຫລວງນ້ຳທາ - Luangnamtha'), ('ບໍ່ແກ້ວ - Borkeo', 'ບໍ່ແກ້ວ - Borkeo'), ('ອຸດົມໄຊ - Oudomxay', 'ອຸດົມໄຊ - Oudomxay'), ('ໄຊຍະບູລີ - Xayaburi', 'ໄຊຍະບູລີ - Xayaburi'), ('ຫລວງພະບາງ - Luangprabang', 'ຫລວງພະບາງ - Luangprabang'), ('ຫົວພັນ - Houaphan', 'ຫົວພັນ - Houaphan'), ('ຊຽງຂວາງ - Xiangkhouang', 'ຊຽງຂວາງ - Xiangkhouang'), ('ແຂວງວຽງຈັນ - Vientiane Province', 'ແຂວງວຽງຈັນ - Vientiane Province'), ('ນະຄອນຫລວງວຽງຈັນ - Vientiane Capital', 'ນະຄອນຫລວງວຽງຈັນ - Vientiane Capital'), ('ໄຊສົມບູນ - Xaisomboun', 'ໄຊສົມບູນ - Xaisomboun'), ('ບໍລິຄຳໄຊ - Borlikhamxai', 'ບໍລິຄຳໄຊ - Borlikhamxai'), ('ຄຳມ່ວນ - Khammouan', 'ຄຳມ່ວນ - Khammouan'), ('ສະຫວັນນະເຂດ - Salavan', 'ສະຫວັນນະເຂດ - Salavan'), ('ສາລະວັນ - Salavan', 'ສາລະວັນ - Salavan'), ('ເຊກອງ - Attapeu', 'ເຊກອງ - Attapeu'), ('ຈຳປາສັກ - Champasak', 'ຈຳປາສັກ - Champasak'), ('ອັດຕະປື - Attapeu', 'ອັດຕະປື - Attapeu')], max_length=50, verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['id'],
            },
        ),
    ]
